name: simple_quran
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.12
  flutter_screenutil: ^5.5.4
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  i_packages:
    path: ../i_packages
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  wakelock: ^0.6.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.2
  dart_code_metrics: ^4.19.1
  flutter_gen_runner: ^5.0.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.0

flutter_gen:
  output: lib/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
  fonts:
    - family: IsepMisbah
      fonts:
        - asset: assets/fonts/LPMQ-IsepMisbah.ttf

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # color is the only required parameter.  It sets the background color of your splash screen.
  color: "#fafafa"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specifiy an image used in the splash screen.  It must be a
  # png file.
  image: assets/icons/icon.png

  # The color_dark and image_dark are parameters that set the color and image when the device is
  # in dark mode.  If they are not specified, the app will use the color and image above.
  # If the image_dark parameter is specified, color_dark must be specified.
  color_dark: "#60668A"
  image_dark: assets/icons/icon.png

  # The android and ios parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: false

  # The position of the splash image can be set with android_gravity and ios_content_mode
  # parameters.  Both default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: clip_horizontal|clip_vertical
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  # To hide the notification bar on Android, use the android_fullscreen parameter.  Defaults to
  # false.
  android_fullscreen: true
